#!/usr/bin/env php
<?php

(@include_once __DIR__ . '/vendor/autoload.php') || @include_once __DIR__ . '/../../autoload.php';

use Symfony\Component\Console\Application;
use Bab\InfluxDB\Command;

$application = new Application();

$application->add(new Command\ClusterAdminsCreateCommand());
$application->add(new Command\ClusterAdminsDeleteCommand());
$application->add(new Command\ClusterAdminsShowCommand());
$application->add(new Command\ClusterServersCommand());
$application->add(new Command\DbCreateCommand());
$application->add(new Command\DbDeleteCommand());
$application->run();
